### ISSUE TITLE
Widget Issues

### ISSUE THREAD

**Issue by bakinazik** [majonez/newsfeed-launcher#2]
Folder Widget app not working on this launcher. Can you check why is this happening? That app works every launcher except yours.

Android 14, AOSP
POCO F2 PRO, LMI
27.0.0/beta01

[https://play.google.com/store/apps/details?id=pub.hanks.appfolderwidget](https://play.google.com/store/apps/details?id=pub.hanks.appfolderwidget)

**Comment by oraveczandrew** [comment]
Hi,

Thanks for your feedback!
I was able to reproduce the issue, it will be fixed in the next version.
